spring.application.name=PayU
server.port=8081
payu.key=sSaf0k
payu.salt=W22A1CzrHMitv0hsIjkBrApr9p4aIBHR

payu.uat_url=https://test.payu.in/_payment
payu.uat_verify-url=https://test.payu.in/merchant/postservice.php?form=2
payu.successurl=http://localhost:8081/payu/payment-response
payu.failureurl=http://localhost:8081/payu/payment-response


payu.prod_url=https://secure.payu.in/_payment
payu.prod_verify-url=https://info.payu.in/merchant/postservice.php?form=2

#Form	Meaning	Output format
#form=1	HTML response (browser-style)	HTML
#form=2	API response	JSON
#form=3	Legacy/internal formats (rare)	varies


#For H2 console http://localhost:8081/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update


spring.datasource.url=jdbc:h2:file:C:/Users/admin/test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect